obj-$(CONFIG_QRTR) := qrtr-core.o
qrtr-core-y	:= qrtr.o
qrtr-core-$(CONFIG_QRTR_IPC_ROUTER_COMPAT) += msm_ipc_compat.o

obj-$(CONFIG_QRTR_SMD) += qrtr-smd.o
qrtr-smd-y	:= smd.o

obj-$(CONFIG_QRTR_MHI) += qrtr-mhi.o
qrtr-mhi-y	:= mhi.o

obj-$(CONFIG_QRTR_USB) += qrtr-usb.o
qrtr-usb-y      := usb.o

obj-$(CONFIG_QRTR_FIFO) += qrtr-fifo.o
qrtr-fifo-y	:= fifo.o

obj-$(CONFIG_QRTR_MHI_DEV) += qrtr-mhi-dev.o
qrtr-mhi-dev-y	:= mhi_dev.o
